"""
Legacy database utility — prefer db_all_articles.py for news/saved-article operations.

This module exists for backward compatibility with any code that already imports
from it. New code should use services/db_all_articles.py instead, which has a cleaner
structure and no cross-layer imports.

───────────────────────────────────────────────────────────────────────────────
NOTE ON EMBEDDINGS (not yet implemented):
  Article embeddings are generated by recommender/embedder.py (Embedder class)
  using sentence-transformers (all-MiniLM-L6-v2, 384-dim vectors).
  Once the embedder is live:
    - News.embedding column is populated by a background job
    - recommender/ranker.py (Ranker class) scores articles via cosine similarity
      against the user's interest_vector from survey_preferences
    - Personalised ranking in agent_service.py (_get_personalized_recommendations)
      will use ranker.rank_articles() instead of the current category-weight fallback

  Any function that reads/writes News.embedding is commented out below.
───────────────────────────────────────────────────────────────────────────────
"""

from ..db.base import Base
from ..db.session import SessionLocal, engine
from ..models.news import News                         # main article table
from ..models.save_article import SavedArticle          # user-bookmarked articles
from ..models.survey import SurveyPreference            # onboarding survey results
from ..models.user import User                          # user accounts
from ..models.user_interaction import UserInteraction   # read/like/save interactions


def create_tables():
    """Create all tables defined by registered ORM models."""
    Base.metadata.create_all(bind=engine)


def insert_user(email: str, password: str):
    """Create a new user account."""
    db = SessionLocal()
    try:
        user = User(email=email, password=password)
        db.add(user)
        db.commit()
        db.refresh(user)
        return user
    finally:
        db.close()


def insert_survey_preference(user_id: int, category: str):
    """Store a user's survey preference (category selection)."""
    db = SessionLocal()
    try:
        preference = SurveyPreference(user_id=user_id, category=category)
        db.add(preference)
        db.commit()
        db.refresh(preference)
        return preference
    finally:
        db.close()


def insert_article(
    title: str,
    description: str | None,
    url: str | None,
    category: str | None,
    source: str | None,
    published_date: str | None,
    img_url: str | None,
    language: str | None,
):
    """
    Insert a raw article into the news table.
    Fields like summary and embedding are set separately by background jobs.
    """
    db = SessionLocal()
    try:
        article = News(
            title=title,
            description=description,
            url=url,
            category=category,
            source=source,
            published_date=published_date,
            image_url=img_url,
            language=language,
        )
        db.add(article)
        db.commit()
        db.refresh(article)
        return article
    finally:
        db.close()


def get_news():
    """
    Return all articles that have a summary (fully processed).
    Uses News.summary as the signal for completion — content may be None.
    """
    db = SessionLocal()
    try:
        articles = db.query(News).filter(News.summary.isnot(None)).all()
        return [
            {
                "article_id": a.article_id,
                "title": a.title,
                "preview": a.summary or a.description,
                "cover_image": a.image_url,
                "date": a.published_date,
                "content": a.content,
                "source": a.source,
                "url": a.url,
                "category": a.category,
                "author": a.author,
            }
            for a in articles
        ]
    finally:
        db.close()


# ── EMBEDDING-RELATED (not yet implemented) ───────────────────────────────────
# Once recommender/embedder.py is live, these functions become active.
# Article embeddings (384-dim vectors) are stored in News.embedding and used by
# recommender/ranker.py to rank articles by cosine similarity against the user's
# interest_vector from survey_preferences.

# def get_articles_needing_embedding(db: Session, limit: int = 100):
#     """Return articles with content but no embedding (for background embedding job)."""
#     return (
#         db.query(News)
#         .filter(News.content.isnot(None))
#         .filter(News.embedding.is_(None))
#         .limit(limit)
#         .all()
#     )
#
# def save_article_embedding(db: Session, article_id: int, embedding: list[float]):
#     """Persist a 384-dim embedding vector to the news row."""
#     article = db.query(News).filter(News.article_id == article_id).first()
#     if article:
#         article.embedding = embedding
#         db.commit()


def log_interaction(user_id: int, article_id: int, interaction_type: str):
    """
    Record a user–article interaction (e.g. "read", "like", "share").
    Interaction data feeds interest_vector updates in recommender/interest_vector.py
    (not yet implemented).
    """
    db = SessionLocal()
    try:
        interaction = UserInteraction(
            user_id=user_id,
            article_id=article_id,
            action=interaction_type,
        )
        db.add(interaction)
        db.commit()
        db.refresh(interaction)
        return interaction
    finally:
        db.close()


if __name__ == "__main__":
    create_tables()